// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0QL5g6JmuqCBi7aGbcwd4GG1TH_gCz9w',
    appId: '1:75404397883:web:e92b05563a91e06bef7b1e',
    messagingSenderId: '75404397883',
    projectId: 'recipeappauth-9b448',
    authDomain: 'recipeappauth-9b448.firebaseapp.com',
    storageBucket: 'recipeappauth-9b448.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwZfMrOFPRBUkv__4j6McLBSnr_WZnqg',
    appId: '1:75404397883:android:ab062eba6261f4f6ef7b1e',
    messagingSenderId: '75404397883',
    projectId: 'recipeappauth-9b448',
    storageBucket: 'recipeappauth-9b448.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCemxeHCYxhH9guM16w_bMUph6c55PZDIA',
    appId: '1:75404397883:ios:163a4b4465559d5bef7b1e',
    messagingSenderId: '75404397883',
    projectId: 'recipeappauth-9b448',
    storageBucket: 'recipeappauth-9b448.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
